### PR TITLE
Extend code to support UIWebView #15

### PR DESCRIPTION
**Pull request by ahalls**

### CODE REVIEW

**Comment by bradmartin** [comment]
Trying to get to this soon and publish the update to npm @ahalls - kinda taking it easy during the end of year.

**Comment by ahalls** [comment]
@bradmartin  I'm starting to do another round of development on my app that makes use of this code.  Can we get this merged into the released plugin soon?

**Comment by bradmartin** [comment]
Dang. I thought I did this one last week :/ sorry. Yea I'll get to it tonight or tomorrow. Ping me same time tmrw if I haven't and I'll get on then and do it. Putting in calendar for tmrw morning reminder. Sorry it slipped.

**Comment by bradmartin** [comment]
Closes #15

**Pull request merged**
